### ISSUE TITLE
Decrease the font in the command box so they can see the full message without scrolling

### ISSUE THREAD

**Issue by t-cheepeng** [AY1920S1-CS2103T-T09-2/main#187]
Should we decrease the font in the command box so they can see the full message without scrolling? A lot of people can't use the app properly because our UG isn't updated and our Error Message is not fully shown

_Originally posted by @garylyp in https://github.com/AY1920S1-CS2103T-T09-2/main/issues/181#issuecomment-549022986_

**Comment by weihaw08** [comment]
Decreasing the font might not be a good idea as it might be too small for the user to see.

**Comment by t-cheepeng** [comment]
maybe increasing the window size of command box will work better

**Comment by t-cheepeng** [comment]
UG Updated in latest PR: #231
