### ISSUE TITLE
Index of exercises changes after editing - wrong exercise selected

### ISSUE THREAD

**Issue by qiujiaaa** [AY1920S1-CS2103T-T09-2/main#212]
Not sure if it is the intended behavior, but the index of the exercises changes sometimes after editing, hence the exercise selected/shown after the command is executed is not the exercise that was edited. 

Initially, the sequence of exercise is this:
![Capture](https://user-images.githubusercontent.com/50521015/68289376-f0afdf00-00c0-11ea-9eed-62187c4c2458.PNG)

After entering `edit i/2 n/Running d/20/09/2019`, the edited exercise shifted to index 3, yet the details for exercise at index 2 is shown (even though it is not the edited one) - bench press is edited but swim is shown instead. 
![Capture(2)](https://user-images.githubusercontent.com/50521015/68289426-0cb38080-00c1-11ea-9fcc-5611a5226761.PNG)

**Comment by garylyp** [comment]
Addressed this issue in PR `fix-bug-add-docs` by amending the `setExercise(ex1, ex2)` method in ModelManager so that the changes to the ExerciseBook triggers the listener correctly in ResourceListPanel.
