### ISSUE TITLE
UG - Suggest command is case-sensitive 

### ISSUE THREAD

**Issue by zhixianggg** [AY1920S1-CS2103T-T09-2/main#217]
I notice that the suggest command is case-sensitive. However, your UG did not mention whether it was supposed to be case-sensitive or not.

Initially, I typed in `suggest s/possible o/or m/legs m/calves` and the result was:

<img width="1512" alt="Screenshot 2019-11-06 at 11 23 31 PM" src="https://user-images.githubusercontent.com/11069609/68311417-7ac16d00-00ec-11ea-8097-459624a4a8d9.png">

When I typed in `suggest s/possible o/or m/Legs m/Calves`, the result was:

<img width="1512" alt="Screenshot 2019-11-06 at 11 24 25 PM" src="https://user-images.githubusercontent.com/11069609/68311518-9cbaef80-00ec-11ea-99ee-7e4c1c083728.png">

**Comment by t-cheepeng** [comment]
@kwekke please document it in the UG
