### ISSUE TITLE
Error message for delete command incomplete

### ISSUE THREAD

**Issue by uberSaiyan** [AY1920S1-CS2103T-T09-2/main#223]
`EXERCISE: null`
![image](https://user-images.githubusercontent.com/38805490/68315134-4c469080-00f2-11ea-86a9-0c52a83e9acf.png)

**Comment by t-cheepeng** [comment]
duplicate. unable to reproduce. pray and hope that this error does not come up
@garylyp @kwekke @jietung @weihaw08
