### ISSUE TITLE
Undo Command wipes out exercises

### ISSUE THREAD

**Issue by zhixianggg** [AY1920S1-CS2103T-T09-2/main#224]
Steps to reproduce error.

1. `schedule n/Level 3 d/12/12/2019`

<img width="1512" alt="Screenshot 2019-11-07 at 12 14 36 AM" src="https://user-images.githubusercontent.com/11069609/68316004-aac03e80-00f3-11ea-86fc-aa57627f80f0.png">

2. `schedule i/1`

<img width="1512" alt="Screenshot 2019-11-07 at 12 14 44 AM" src="https://user-images.githubusercontent.com/11069609/68316011-ad229880-00f3-11ea-8f12-76df3c7e5aee.png">

3. `undo`

<img width="1512" alt="Screenshot 2019-11-07 at 12 14 57 AM" src="https://user-images.githubusercontent.com/11069609/68316015-af84f280-00f3-11ea-84d2-d9e950700780.png">

**Comment by t-cheepeng** [comment]
intended behaviour not a bug
