### ISSUE TITLE
Clear not working properly (maybe its just display)

### ISSUE THREAD

**Issue by uberSaiyan** [AY1920S1-CS2103T-T09-2/main#227]
Steps to reproduce:
1. Create custom prefix (prefix=N, fullName=Namu)
2. Attach this custom prefix to an exercise
3. Delete this custom prefix
4. Execute `clear`
5. The screen below should appear

![image](https://user-images.githubusercontent.com/38805490/68318751-363bce80-00f8-11ea-98a6-d76d37483c80.png)

**Comment by t-cheepeng** [comment]
Was unable to reproduce this error. Anyone able to reproduce it?
@kwekke @garylyp @jietung @weihaw08

**Comment by weihaw08** [comment]
I was unable to reproduce this error too.

**Comment by jietung** [comment]
nope

**Comment by garylyp** [comment]
Addressed this issue in PR `fix-bug-add-docs`. Apparently, clear command returns a CommandResult with `ListResourceType.SUGGEST` as list type. My bad.
