### ISSUE TITLE
Edit Command Accepts Invalid Inputs

### ISSUE THREAD

**Issue by garylyp** [AY1920S1-CS2103T-T09-2/main#82]
Component: 
-EditCommand
-EditCommandParser

Description:
-Program accepts invalid inputs even if fields are invalid
-Fields are then updated with the invalid inputs
-Problem already exists since code base refactoring in #13 

Steps: 
1) Enter the following input "edit 1 q/23@sfgh2" 

Expected:
1) Program sends user a warning in the response box and do not update the field

Actual:
1) The quantity field of the exercise at position 1 changes to "23@sfgh2"

**Comment by weihaw08** [comment]
It is actually not an issue with EditCommand and EditCommandParser. 

As of now, the Units class has not been implemented. So, the Quantity class allows anything except for an empty string as a parameter. 

@jietung, you may want to make amendments to the validation regex after you have implemented the Units class.

**Comment by t-cheepeng** [comment]
> 
> 
> It is actually not an issue with the EditCommand and EditCommandParser.
> 
> As of now, the Units class has not been implemented. So, the Quantity class allows anything except for an empty string as a parameter.
> 
> @jietung, you may want to make amendments to the validation regex for the Quantity class after you have implemented the Units class.

Either way we will keep the bug report alive and assign it to the PR/commit that will solve it eventually. This is also a nice way to remind us that this issue exists for the current version of ExerHealth instead of some future version so we will not forget to change the required components in the future.

**Comment by t-cheepeng** [comment]
Fixed by PR: #81
