### ISSUE TITLE
Unit Tests missing for Unit class 

### ISSUE THREAD

**Issue by t-cheepeng** [AY1920S1-CS2103T-T09-2/main#85]
Units tests are incomplete for `AddCommandParserTest` in method `parse_compulsoryFieldMissing_failure`. Some fields which are not compulsory have been made compulsory.

Unit tests are missing in `ParserUtilTest`. All methods related to `parseUnit` are missing unit tests

Unit tests in `EditCommandParserTest` are incomplete in methods like `parse_allFieldsSpecified_success` and `parse_oneFieldSpecified_success`. All tests mentioned do not have units in it

**Comment by jietung** [comment]
Deleted tests in `AddCommandParserTest` , method `parse_compulsoryFieldMissing_failure`. 
Only left compulsory name and date.
Added test in `ParserUtilTest` for `parseUnit`.
Added tests in `EditCommandParserTest`.
Edits are in Morph branch.
